-- noinspection SqlResolveForFile
-- @author: bht

ALTER DATABASE [AUTH] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE [AUTH]
GO

ALTER DATABASE [USER] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE [USER]
GO

ALTER DATABASE [PARKINGLOT] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE [PARKINGLOT]
GO