-- noinspection SqlResolveForFile
-- @author: bht

USE [USER]
GO

ALTER TABLE [CUSTOMER] ADD  CONSTRAINT [DF_CUSTOMER_LAST_UPDATED]  DEFAULT (getdate()) FOR [LAST_UPDATED]
GO
ALTER TABLE [USER] ADD  CONSTRAINT [DF_USER_IS_ACTIVATED]  DEFAULT ((0)) FOR [IS_ACTIVATED]
GO
ALTER TABLE [USER] ADD  CONSTRAINT [DF_USER_LAST_SIGN_IN]  DEFAULT (getdate()) FOR [LAST_SIGN_IN]
GO
ALTER TABLE [USER] ADD  CONSTRAINT [DF_USER_VERSION]  DEFAULT ((1)) FOR [VERSION]
GO
ALTER TABLE [USER_ROLE] ADD  CONSTRAINT [DF_USER_ROLE_VERSION]  DEFAULT ((1)) FOR [VERSION]
GO