-- noinspection SqlResolveForFile
-- @author: bht

USE [USER]
GO

ALTER TABLE [CUSTOMER]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMER_USER] FOREIGN KEY([ID])
REFERENCES [USER] ([ID])
GO
ALTER TABLE [CUSTOMER] CHECK CONSTRAINT [FK_CUSTOMER_USER]
GO
ALTER TABLE [PARKING_LOT_EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_PARKING_LOT_EMPLOYEE_USER] FOREIGN KEY([ID])
REFERENCES [USER] ([ID])
GO
ALTER TABLE [PARKING_LOT_EMPLOYEE] CHECK CONSTRAINT [FK_PARKING_LOT_EMPLOYEE_USER]
GO
ALTER TABLE [USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_USER_ROLE] FOREIGN KEY([ROLE_ID])
REFERENCES [USER_ROLE] ([ID])
GO
ALTER TABLE [USER] CHECK CONSTRAINT [FK_USER_USER_ROLE]
GO