-- noinspection SqlResolveForFile
-- @author: bht
USE [PARKINGMAP]
GO
ALTER TABLE [CUSTOMER]
    WITH CHECK ADD CONSTRAINT [FK_CUSTOMER_USER] FOREIGN KEY ([ID])
        REFERENCES [USER] ([ID])
GO
ALTER TABLE [CUSTOMER]
    CHECK CONSTRAINT [FK_CUSTOMER_USER]
GO
ALTER TABLE [PARKING_LOT]
    WITH CHECK ADD CONSTRAINT [FK_PARKING_LOT_PARKING_LOT_TYPE] FOREIGN KEY ([PARKING_LOT_TYPE_ID])
        REFERENCES [PARKING_LOT_TYPE] ([ID])
GO
ALTER TABLE [PARKING_LOT]
    CHECK CONSTRAINT [FK_PARKING_LOT_PARKING_LOT_TYPE]
GO
ALTER TABLE [PARKING_LOT_EMPLOYEE]
    WITH CHECK ADD CONSTRAINT [FK_PARKING_LOT_EMPLOYEE_PARKING_LOT] FOREIGN KEY ([PARKING_LOT_ID])
        REFERENCES [PARKING_LOT] ([ID])
GO
ALTER TABLE [PARKING_LOT_EMPLOYEE]
    CHECK CONSTRAINT [FK_PARKING_LOT_EMPLOYEE_PARKING_LOT]
GO
ALTER TABLE [PARKING_LOT_EMPLOYEE]
    WITH CHECK ADD CONSTRAINT [FK_PARKING_LOT_EMPLOYEE_USER] FOREIGN KEY ([ID])
        REFERENCES [USER] ([ID])
GO
ALTER TABLE [PARKING_LOT_EMPLOYEE]
    CHECK CONSTRAINT [FK_PARKING_LOT_EMPLOYEE_USER]
GO
ALTER TABLE [PARKING_LOT_INFORMATION]
    WITH CHECK ADD CONSTRAINT [FK_PARKING_LOT_INFORMATION_PARKING_LOT] FOREIGN KEY ([ID])
        REFERENCES [PARKING_LOT] ([ID])
GO
ALTER TABLE [PARKING_LOT_INFORMATION]
    CHECK CONSTRAINT [FK_PARKING_LOT_INFORMATION_PARKING_LOT]
GO
ALTER TABLE [PARKING_LOT_LIMIT]
    WITH CHECK ADD CONSTRAINT [FK_PARKING_LOT_LIMIT_PARKING_LOT] FOREIGN KEY ([ID])
        REFERENCES [PARKING_LOT] ([ID])
GO
ALTER TABLE [PARKING_LOT_LIMIT]
    CHECK CONSTRAINT [FK_PARKING_LOT_LIMIT_PARKING_LOT]
GO
ALTER TABLE [PARKING_LOT_RATING]
    WITH CHECK ADD CONSTRAINT [FK_PARKING_LOT_RATING_CUSTOMER] FOREIGN KEY ([CUSTOMER_ID])
        REFERENCES [CUSTOMER] ([ID])
GO
ALTER TABLE [PARKING_LOT_RATING]
    CHECK CONSTRAINT [FK_PARKING_LOT_RATING_CUSTOMER]
GO
ALTER TABLE [PARKING_LOT_RATING]
    WITH CHECK ADD CONSTRAINT [FK_PARKING_LOT_RATING_PARKING_LOT] FOREIGN KEY ([PARKING_LOT_ID])
        REFERENCES [PARKING_LOT] ([ID])
GO
ALTER TABLE [PARKING_LOT_RATING]
    CHECK CONSTRAINT [FK_PARKING_LOT_RATING_PARKING_LOT]
GO
ALTER TABLE [PARKING_LOT_SUGGESTION]
    WITH CHECK ADD CONSTRAINT [FK_PARKING_LOT_SUGGESTION_CUSTOMER] FOREIGN KEY ([CUSTOMER_ID])
        REFERENCES [CUSTOMER] ([ID])
GO
ALTER TABLE [PARKING_LOT_SUGGESTION]
    CHECK CONSTRAINT [FK_PARKING_LOT_SUGGESTION_CUSTOMER]
GO
ALTER TABLE [PARKING_LOT_UNIT]
    WITH CHECK ADD CONSTRAINT [FK_PARKING_LOT_UNIT_PARKING_LOT] FOREIGN KEY ([PARKING_LOT_ID])
        REFERENCES [PARKING_LOT] ([ID])
GO
ALTER TABLE [PARKING_LOT_UNIT]
    CHECK CONSTRAINT [FK_PARKING_LOT_UNIT_PARKING_LOT]
GO
ALTER TABLE [USER]
    WITH CHECK ADD CONSTRAINT [FK_USER_USER_ROLE] FOREIGN KEY ([ROLE_ID])
        REFERENCES [USER_ROLE] ([ID])
GO
ALTER TABLE [USER]
    CHECK CONSTRAINT [FK_USER_USER_ROLE]
GO
ALTER TABLE [PARKING_LOT]
    WITH CHECK ADD CONSTRAINT [CK_PARKING_LOT_VALID_CLOSING_HOUR] CHECK (([CLOSING_HOUR] > [OPENING_HOUR]))
GO
ALTER TABLE [PARKING_LOT]
    CHECK CONSTRAINT [CK_PARKING_LOT_VALID_CLOSING_HOUR]
GO
ALTER TABLE [PARKING_LOT_LIMIT]
    WITH CHECK ADD CONSTRAINT [CK_PARKING_LOT_LIMIT_VALID] CHECK (([AVAILABILITY] >= (0) AND [AVAILABILITY] <= [CAPACITY]))
GO
ALTER TABLE [PARKING_LOT_LIMIT]
    CHECK CONSTRAINT [CK_PARKING_LOT_LIMIT_VALID]
GO
ALTER TABLE [PARKING_LOT_RATING]
    WITH CHECK ADD CONSTRAINT [CK_PARKING_LOT_RATING] CHECK (([RATING] = (5) OR [RATING] = (4) OR [RATING] = (3) OR
                                                              [RATING] = (2) OR [RATING] = (1)))
GO
ALTER TABLE [PARKING_LOT_RATING]
    CHECK CONSTRAINT [CK_PARKING_LOT_RATING]
GO