-- noinspection SqlResolveForFile
-- @author: bht

USE PARKINGMAP
GO

DECLARE
    @LATITUDE FLOAT = 10.784122211291663
DECLARE
    @LONGITUDE FLOAT= 106.71152489259839
DECLARE
    @RADIUS INT = 3


-- WITH PARKING-LOT NAME
SELECT TOP 5 P.ID,
             PLI.NAME,
             P.PARKING_LOT_TYPE_ID,
             P.LATITUDE,
             P.LONGITUDE,
             dbo.GET_DISTANCE_IN_KILOMETRE(@LATITUDE, @LONGITUDE, P.LATITUDE, P.LONGITUDE) AS DISTANCE
FROM PARKING_LOT P
         INNER JOIN (SELECT ID, NAME FROM PARKING_LOT_INFORMATION) AS PLI ON PLI.ID = P.ID
    AND 1 =
        DBO.IS_VALUE_IN_BOUND(P.LATITUDE, @LATITUDE, DBO.CALCULATE_DELTA_LAT_IN_DEGREE(@LATITUDE, @LONGITUDE, @RADIUS))
    AND 1 = DBO.IS_VALUE_IN_BOUND(P.LONGITUDE, @LONGITUDE,
                                  DBO.CALCULATE_DELTA_LNG_IN_DEGREE(@LATITUDE, @LONGITUDE, @RADIUS))
    AND IS_AVAILABLE = 1
    AND CONVERT(TIME, GETDATE()) BETWEEN P.OPENING_HOUR AND P.CLOSING_HOUR
ORDER BY DISTANCE


-- WITHOUT PARKING-LOT NAME
SELECT TOP 10 P.ID,
              P.PARKING_LOT_TYPE_ID,
              P.LATITUDE,
              P.LONGITUDE,
              dbo.GET_DISTANCE_IN_KILOMETRE(@LATITUDE, @LONGITUDE, P.LATITUDE, P.LONGITUDE) AS DISTANCE
FROM PARKING_LOT P
WHERE 1 =
      DBO.IS_VALUE_IN_BOUND(P.LATITUDE, @LATITUDE, DBO.CALCULATE_DELTA_LAT_IN_DEGREE(@LATITUDE, @LONGITUDE, @RADIUS))
  AND 1 =
      DBO.IS_VALUE_IN_BOUND(P.LONGITUDE, @LONGITUDE, DBO.CALCULATE_DELTA_LNG_IN_DEGREE(@LATITUDE, @LONGITUDE, @RADIUS))
  AND IS_AVAILABLE = 1
  AND CONVERT(TIME, GETDATE()) BETWEEN P.OPENING_HOUR AND P.CLOSING_HOUR
ORDER BY DISTANCE