-- noinspection SqlResolveForFile

USE PARKINGMAP
GO

DECLARE
    @LATITUDE FLOAT
DECLARE
    @LONGITUDE FLOAT
DECLARE
    @RADIUS SMALLINT

SET @LATITUDE = 10.784122211291663
SET @LONGITUDE = 106.71152489259839
SET @RADIUS = 3

SELECT TOP 10 P.ID,
              PLI.NAME,
              P.PARKING_LOT_TYPE_ID,
              P.LATITUDE,
              P.LONGITUDE,
              P.OPENING_HOUR,
              P.CLOSING_HOUR,
              P.LAST_UPDATED,
              DISTANCE
FROM PARKING_LOT P
         INNER JOIN (
    SELECT ID, NAME
    FROM PARKING_LOT_INFORMATION) AS PLI ON PLI.ID = P.ID
         INNER JOIN (
    SELECT PL.ID, dbo.GET_DISTANCE_IN_KILOMETRE(@LATITUDE, @LONGITUDE, PL.LATITUDE, PL.LONGITUDE) AS DISTANCE
    FROM PARKING_LOT PL) AS PL
                    ON P.ID = PL.ID AND DISTANCE <= @RADIUS AND IS_AVAILABLE = 1
                        AND CONVERT(TIME, GETDATE()) BETWEEN P.OPENING_HOUR AND P.CLOSING_HOUR
ORDER BY DISTANCE