-- noinspection SqlNoDataSourceInspectionForFile
-- noinspection SqlDialectInspectionForFile
-- noinspection SqlResolveForFile
-- @author: bht

CREATE DATABASE [AUTH]
ALTER DATABASE [AUTH] SET AUTO_CLOSE OFF WITH NO_WAIT
GO

CREATE DATABASE [USER]
ALTER DATABASE [USER] SET AUTO_CLOSE OFF WITH NO_WAIT
GO

CREATE DATABASE [PARKINGLOT]
ALTER DATABASE [PARKINGLOT] SET AUTO_CLOSE OFF WITH NO_WAIT
GO

CREATE DATABASE [BOOKING]
ALTER DATABASE [BOOKING] SET AUTO_CLOSE OFF WITH NO_WAIT
GO