-- noinspection SqlNoDataSourceInspectionForFile
-- noinspection SqlDialectInspectionForFile
-- noinspection SqlResolveForFile
-- @author: bht

USE [AUTH]
GO
ALTER AUTHORIZATION ON DATABASE::[AUTH] TO [sa]
GO

USE [PARKINGLOT]
GO
ALTER AUTHORIZATION ON DATABASE::[PARKINGLOT] TO [sa]
GO

USE [USER]
GO
ALTER AUTHORIZATION ON DATABASE::[USER] TO [sa]
GO

USE [BOOKING]
GO
ALTER AUTHORIZATION ON DATABASE::[BOOKING] TO [sa]
GO