-- noinspection SqlResolveForFile
-- @author: bht
USE [PARKINGMAP]
GO
ALTER TABLE [CUSTOMER]
    ADD CONSTRAINT [DF_CUSTOMER_LAST_UPDATED] DEFAULT (getdate()) FOR [LAST_UPDATED]
GO
ALTER TABLE [PARKING_LOT]
    ADD CONSTRAINT [DF_PARKING_LOT_IS_AVAILABLE] DEFAULT ((0)) FOR [IS_AVAILABLE]
GO
ALTER TABLE [PARKING_LOT]
    ADD CONSTRAINT [DF_PARKING_LOT_VERSION] DEFAULT ((1)) FOR [VERSION]
GO
ALTER TABLE [PARKING_LOT_INFORMATION]
    ADD CONSTRAINT [DF_PARKING_LOT_RATING_AVERAGE] DEFAULT ((0)) FOR [RATING_AVERAGE]
GO
ALTER TABLE [PARKING_LOT_INFORMATION]
    ADD CONSTRAINT [DF_PARKING_LOT_NUMBER_OF_RATING] DEFAULT ((0)) FOR [NUMBER_OF_RATING]
GO
ALTER TABLE [PARKING_LOT_INFORMATION]
    ADD CONSTRAINT [DF_PARKING_LOT_INFORMATION_VERSION] DEFAULT ((1)) FOR [VERSION]
GO
ALTER TABLE [PARKING_LOT_LIMIT]
    ADD CONSTRAINT [DF_PARKING_LOT_LIMIT_CAPACITY] DEFAULT ((0)) FOR [CAPACITY]
GO
ALTER TABLE [PARKING_LOT_LIMIT]
    ADD CONSTRAINT [DF_PARKING_LOT_LIMIT_AVAILABILITY] DEFAULT ((0)) FOR [AVAILABILITY]
GO
ALTER TABLE [PARKING_LOT_LIMIT]
    ADD CONSTRAINT [DF_PARKING_LOT_LIMIT_VERSION] DEFAULT ((1)) FOR [VERSION]
GO
ALTER TABLE [PARKING_LOT_RATING]
    ADD CONSTRAINT [DF_PARKING_LOT_RATING_LAST_UPDATED] DEFAULT (getdate()) FOR [LAST_UPDATED]
GO
ALTER TABLE [PARKING_LOT_RATING]
    ADD CONSTRAINT [DF_PARKING_LOT_RATING_VERSION] DEFAULT ((1)) FOR [VERSION]
GO
ALTER TABLE [PARKING_LOT_SUGGESTION]
    ADD CONSTRAINT [DF_PARKING_LOT_SUGGESTION_IS_HANDLED] DEFAULT ((0)) FOR [IS_HANDLED]
GO
ALTER TABLE [PARKING_LOT_SUGGESTION]
    ADD CONSTRAINT [DF_PARKING_LOT_SUGGESTION_LAST_UPDATED] DEFAULT (getdate()) FOR [LAST_UPDATED]
GO
ALTER TABLE [PARKING_LOT_SUGGESTION]
    ADD CONSTRAINT [DF_PARKING_LOT_SUGGESTION_VERSION] DEFAULT ((1)) FOR [VERSION]
GO
ALTER TABLE [PARKING_LOT_TYPE]
    ADD CONSTRAINT [DF_PARKING_LOT_TYPE_VERSION] DEFAULT ((1)) FOR [VERSION]
GO
ALTER TABLE [PARKING_LOT_UNIT]
    ADD CONSTRAINT [DF_PARKING_LOT_UNIT_LAST_UPDATED] DEFAULT (getdate()) FOR [LAST_UPDATED]
GO
ALTER TABLE [PARKING_LOT_UNIT]
    ADD CONSTRAINT [DF_PARKING_LOT_UNIT_VERSION] DEFAULT ((1)) FOR [VERSION]
GO
ALTER TABLE [USER]
    ADD CONSTRAINT [DF_USER_IS_ACTIVATED] DEFAULT ((0)) FOR [IS_ACTIVATED]
GO
ALTER TABLE [USER]
    ADD CONSTRAINT [DF_USER_LAST_SIGN_IN] DEFAULT (getdate()) FOR [LAST_SIGN_IN]
GO
ALTER TABLE [USER]
    ADD CONSTRAINT [DF_USER_VERSION] DEFAULT ((1)) FOR [VERSION]
GO
ALTER TABLE [USER_ROLE]
    ADD CONSTRAINT [DF_USER_ROLE_VERSION] DEFAULT ((1)) FOR [VERSION]
GO