-- noinspection SqlResolveForFile
-- @author: bht
USE [PARKINGMAP]
GO

ALTER DATABASE [AUTH] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE [AUTH]
GO

ALTER DATABASE [USER] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE [USER]
GO

ALTER DATABASE [PARKINGLOT] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE [PARKINGLOT]
GO

CREATE DATABASE [AUTH]
ALTER DATABASE [AUTH] SET AUTO_CLOSE OFF WITH NO_WAIT
GO

CREATE DATABASE [USER]
ALTER DATABASE [USER] SET AUTO_CLOSE OFF WITH NO_WAIT
GO

CREATE DATABASE [PARKINGLOT]
ALTER DATABASE [PARKINGLOT] SET AUTO_CLOSE OFF WITH NO_WAIT
GO